name: ESLint Validation

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coder-tavi/eslint-action@1.1.1
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          eslint-rc: .eslintrc.js
          execute-on-files: ./
